"""Helpers for curated semantic notes carried from skills to analytical consumers.

Semantic notes are declarative, auxiliary context (for example "this breakdown
uses a different calculation basis than the general KPI"). They are never
generated by a model and must never make an analytical execution fail, so every
helper here is total: malformed input is ignored instead of raised.
"""
from __future__ import annotations

from typing import Any, Iterable

SEMANTIC_NOTES_KEY = "semantic_notes"


def normalize_semantic_notes(value: Any) -> list[str]:
    """Return a clean, deduplicated list of notes; ignore anything malformed.

    Only a list of strings is accepted. Non-string items, blanks and repeated
    notes (compared ignoring case and whitespace differences) are dropped while
    keeping the first occurrence, so the original order is preserved.
    """
    if not isinstance(value, (list, tuple)):
        return []
    notes: list[str] = []
    seen: set[str] = set()
    for item in value:
        if not isinstance(item, str):
            continue
        note = item.strip()
        key = " ".join(note.split()).casefold()
        if not key or key in seen:
            continue
        seen.add(key)
        notes.append(note)
    return notes


def collect_semantic_notes(metadata_items: Iterable[Any]) -> list[str]:
    """Merge the ``semantic_notes`` of several skill metadata dictionaries."""
    merged: list[str] = []
    for metadata in metadata_items:
        if isinstance(metadata, dict):
            merged.extend(normalize_semantic_notes(metadata.get(SEMANTIC_NOTES_KEY)))
    return normalize_semantic_notes(merged)
