"""empty message

Revision ID: 6f3e4fbb14a7
Revises: d40cd067fdb3
Create Date: 2025-12-03 17:43:53.305301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3e4fbb14a7'
down_revision = 'd40cd067fdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_privacidad', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cliente_privado_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'clientes_privados', ['cliente_privado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_privado_id')
        batch_op.drop_column('tipo_privacidad')

    # ### end Alembic commands ###
